name: simple_floating_bottom_nav_bar
description: A simple floating bottom nvigation bar for flutter.
version: 0.0.1
homepage: https://github.com/Strange-Philip/simple_floating_bottom_nav_bar/blob/main/README.md

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
